# Generated by Django 5.1.5 on 2025-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualisationCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_camera', models.TextField()),
                ('date', models.TextField()),
                ('heure', models.TextField()),
                ('video_disponible', models.TextField()),
            ],
            options={
                'db_table': 'alertes_visualisationcamera',
            },
        ),
    ]
